### ISSUE TITLE
"Isolated" invocations of Python installed via setup-python behave differently in Runs-On Ubuntu 24 images vs. Github or Runs-On Ubuntu 22

### ISSUE THREAD

**Issue by huonw** [runs-on/runner-images-for-aws#20]
There is a behaviour difference for "isolated" (i.e. without any environment variables, e.g. by invoking with `env -i ...`) invocations of Pythons installed via https://github.com/actions/setup-python, where the Runs-On x64 Ubuntu24 image fails, compared to 3 other related images all succeeding.

Reproducer, that compares 3 different ways of invoking Python 3.10:

- "normal"
- "isolated": without any environment variables provided (the `$(which python)` is doing the `$PATH` look-up that `env -i` inhibits because `PATH` isn't set).
- "isolate with LD_LIBRARY_PATH": demonstrating a workaround of explicitly passing around LD_LIBRARY_PATH

```yaml
---
name: App

"on":
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/image=ubuntu24-full-x64"
          - "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/image=ubuntu22-full-x64"
          - ubuntu-24.04
          - ubuntu-22.04
         
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Normal invocation"
        run: |
          python -c 'import sys; print(sys.version)'
        if: always()

      - name: "Isolated invocation"
        run: |
          env -i $(which python) -c 'import sys; print(sys.version)'
        if: always()

      - name: "Isolated invocation with LD_LIBRARY_PATH"
        run: |
          env -i LD_LIBRARY_PATH=$LD_LIBRARY_PATH $(which python) -c 'import sys; print(sys.version)'
        if: always()
```

Results:

| runner | normal | isolated | isolated+LD_LIBRARY_PATH |
|---|---|---|---|
| Runs-On ubuntu24 | ✅  | ❌ | ✅ |
| Runs-On ubuntu22 | ✅  | ✅ | ✅ |
| GHA ubuntu24 | ✅ | ✅ | ✅ |
| GHA ubuntu22 | ✅ | ✅ | ✅ |

That is, all the images seem to behave "sensibly"/the same _except_ for Runs-On ubuntu24 not supporting the plain isolated invocation. This is weird to me, and makes me wonder if there's an issue in that image!

Specific output:

- The failure gives error message:

  ```
  /home/runner/_work/_tool/Python/3.10.16/x64/bin/python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
  ```
  
- The successes all say either `3.10.16 (main, Dec 12 2024, 19:07:59) [GCC 13.2.0]` (ubuntu24) or `3.10.16 (main, Dec 12 2024, 19:07:39) [GCC 11.4.0]` (ubuntu22).

(Context: this is relevant to us using https://github.com/pantsbuild/pants, which runs tests (and so on) within sandboxes that use `env -i ...` for isolation.)

As always, thanks for Runs-On!
