### ISSUE TITLE
ARM image: mvn: command not found

### ISSUE THREAD

**Issue by project0** [runs-on/runner-images-for-aws#6]
Looks like mvn ist not installed on the ARM image (while the x86 works fine without problem)

`/home/runner/_work/_temp/4abc1788-93f7-4c17-8d79-de3764d8a67e.sh: line 1: mvn: command not found`

```
  | Region            | eu-central-1                                      |
  | AvailabilityZone  | eu-central-1a                                     |
  | Version           | v2.5.0                                            |
  | Runner            | runs-on--i-04c96861d7bfffd50--onXdTUJgdY          |
  | InstanceId        | i-04c96861d7bfffd50                               |
  | InstanceType      | c7g.2xlarge                                       |
  | InstanceLifecycle | on-demand                                         |
  | InstanceRAM       | 15675.91 MiB                                      |
  | InstanceCPU       | 8 cores                                           |
  | InstanceDisk1     | /=/dev/nvme0n1p1                                  |
  |                   | Free=31.14GiB Used=7.43GiB                        |
  | ImageId           | ami-06be13261bef9cac8                             |
  | ImageName         | runs-on-v2.2-ubuntu22-full-arm64-20240916080532   |
  | Platform          | linux                                             |
  | Architecture      | arm64                                             |
  | Has preinstall    | false                                             |
  | PrivateIp         | 10.1.4.186                                        |
  | Debug             | false                                             |

```

```
jobs:
  test:
    name: Build and test
    # https://runs-on.com/runners/linux/#default-runners
    runs-on:
    - runs-on
    - runner=8cpu-linux-arm64
    - run-id=${{ github.run_id }}
    - spot=price-capacity-optimized
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
      # https://github.com/actions/setup-java
      # use maven cache
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '22'
        cache: maven

    - name: Test application
      id: test
      timeout-minutes: 120
      run: |
        mvn $MAVEN_CLI_OPTS -DskipTests=${{ inputs.skip-tests }} org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
```
